In [ ]:
# Import libraries
import pandas as pd
from sklearn.datasets import load_iris

In [ ]:
# Load iris dataset
iris = load_iris()
# Convert into DataFrame
df = pd.DataFrame(iris.data, columns=iris.feature_names)
# Add target column
df['species'] = iris.target

df.head()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
0,5.1,3.5,1.4,0.2,0
1,4.9,3.0,1.4,0.2,0
2,4.7,3.2,1.3,0.2,0
3,4.6,3.1,1.5,0.2,0
4,5.0,3.6,1.4,0.2,0

In [ ]:
# Shape of dataset
print("Shape:", df.shape)
# Data types
print("\nData Types:")
print(df.dtypes)

Shape: (150, 5)

Data Types:
sepal length (cm)    float64
sepal width (cm)     float64
petal length (cm)    float64
petal width (cm)     float64
species                int64
dtype: object

In [ ]:
# Statistical summary
df.describe()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm),species
count,150.000000,150.000000,150.000000,150.000000,150.000000
mean,5.843333,3.057333,3.758000,1.199333,1.000000
std,0.828066,0.435866,1.765298,0.762238,0.819232
min,4.300000,2.000000,1.000000,0.100000,0.000000
25%,5.100000,2.800000,1.600000,0.300000,0.000000
50%,5.800000,3.000000,4.350000,1.300000,1.000000
75%,6.400000,3.300000,5.100000,1.800000,2.000000
max,7.900000,4.400000,6.900000,2.500000,2.000000

In [ ]:
# Standard deviation grouped by species
df.groupby('species').std()

,sepal length (cm),sepal width (cm),petal length (cm),petal width (cm)
species,,,,
0,0.352490,0.379064,0.173664,0.105386
1,0.516171,0.313798,0.469911,0.197753
2,0.635880,0.322497,0.551895,0.274650

In [ ]:
# Statistics for Setosa species only
setosa = df[df['species'] == 0]

print(setosa.describe())

       sepal length (cm)  sepal width (cm)  petal length (cm)  \
count           50.00000         50.000000          50.000000
mean             5.00600          3.428000           1.462000
std              0.35249          0.379064           0.173664
min              4.30000          2.300000           1.000000
25%              4.80000          3.200000           1.400000
50%              5.00000          3.400000           1.500000
75%              5.20000          3.675000           1.575000
max              5.80000          4.400000           1.900000

       petal width (cm)  species
count         50.000000     50.0
mean           0.246000      0.0
std            0.105386      0.0
min            0.100000      0.0
25%            0.200000      0.0
50%            0.200000      0.0
75%            0.300000      0.0
max            0.600000      0.0

In [ ]:
# Rename columns
df.columns = [
    'sepal_length',
    'sepal_width',
    'petal_length',
    'petal_width',
    'species'
]
df.head()

   sepal_length  sepal_width  petal_length  petal_width  species
0           5.1          3.5           1.4          0.2        0
1           4.9          3.0           1.4          0.2        0
2           4.7          3.2           1.3          0.2        0
3           4.6          3.1           1.5          0.2        0
4           5.0          3.6           1.4          0.2        0

In [ ]:
# Show unique species
df['species'].unique()

array([0, 1, 2])

In [ ]:
iris.target_names

array(['setosa', 'versicolor', 'virginica'], dtype='<U10')

In [ ]:
# Mean grouped by species
df.groupby('species').mean()

         sepal_length  sepal_width  petal_length  petal_width
species
0               5.006        3.428         1.462        0.246
1               5.936        2.770         4.260        1.326
2               6.588        2.974         5.552        2.026

In [ ]:
# Median grouped by species
df.groupby('species').median()

         sepal_length  sepal_width  petal_length  petal_width
species
0                 5.0          3.4          1.50          0.2
1                 5.9          2.8          4.35          1.3
2                 6.5          3.0          5.55          2.0

In [ ]:
# Minimum values grouped by species
df.groupby('species').min()

         sepal_length  sepal_width  petal_length  petal_width
species
0                 4.3          2.3           1.0          0.1
1                 4.9          2.0           3.0          1.0
2                 4.9          2.2           4.5          1.4

In [ ]:
# Minimum values grouped by species
df.groupby('species').max()

         sepal_length  sepal_width  petal_length  petal_width
species
0                 5.8          4.4           1.9          0.6
1                 7.0          3.4           5.1          1.8
2                 7.9          3.8           6.9          2.5

In [ ]:
# Detailed statistics with percentiles
df.groupby('species').describe(percentiles=[0.25, 0.5, 0.75])

        sepal_length                                             sepal_width  \
               count   mean       std  min    25%  50%  75%  max       count
species
0               50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8        50.0
1               50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0        50.0
2               50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9        50.0

                ... petal_length      petal_width                             \
          mean  ...          75%  max       count   mean       std  min  25%
species         ...
0        3.428  ...        1.575  1.9        50.0  0.246  0.105386  0.1  0.2
1        2.770  ...        4.600  5.1        50.0  1.326  0.197753  1.0  1.2
2        2.974  ...        5.875  6.9        50.0  2.026  0.274650  1.4  1.8


         50%  75%  max
species
0        0.2  0.3  0.6
1        1.3  1.5  1.8
2        2.0  2.3  2.5

[3 rows x 32 columns]

In [ ]:
# Detailed statistics with percentiles
df.groupby('species').describe()

        sepal_length                                             sepal_width  \
               count   mean       std  min    25%  50%  75%  max       count
species
0               50.0  5.006  0.352490  4.3  4.800  5.0  5.2  5.8        50.0
1               50.0  5.936  0.516171  4.9  5.600  5.9  6.3  7.0        50.0
2               50.0  6.588  0.635880  4.9  6.225  6.5  6.9  7.9        50.0

                ... petal_length      petal_width                             \
          mean  ...          75%  max       count   mean       std  min  25%
species         ...
0        3.428  ...        1.575  1.9        50.0  0.246  0.105386  0.1  0.2
1        2.770  ...        4.600  5.1        50.0  1.326  0.197753  1.0  1.2
2        2.974  ...        5.875  6.9        50.0  2.026  0.274650  1.4  1.8


         50%  75%  max
species
0        0.2  0.3  0.6
1        1.3  1.5  1.8
2        2.0  2.3  2.5

[3 rows x 32 columns]