In [ ]:
# Import libraries
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

# ML tools
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

# Evaluation metrics
from sklearn.metrics import (
    confusion_matrix,
    accuracy_score,
    precision_score,
    recall_score
)

In [ ]:
# Load CSV file
df = pd.read_csv("Social_Network_Ads.csv")

# Display first 5 rows
df.head()

    User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [ ]:
# Shape of dataset
print("Shape:")
print(df.shape)

# Data types
print("\nData Types:")
print(df.dtypes)

# Missing values
print("\nMissing Values:")
print(df.isnull().sum())

Shape:
(400, 5)

Data Types:
User ID             int64
Gender             object
Age                 int64
EstimatedSalary     int64
Purchased           int64
dtype: object

Missing Values:
User ID            0
Gender             0
Age                0
EstimatedSalary    0
Purchased          0
dtype: int64

In [ ]:
# Features (input)
X = df[['Age', 'EstimatedSalary']]


# Display features
print(X.head())

   Age  EstimatedSalary
0   19            19000
1   35            20000
2   26            43000
3   27            57000
4   19            76000

In [ ]:
# Target (output)
y = df['Purchased']

# Display target
print(y.head())

0    0
1    0
2    0
3    0
4    0
Name: Purchased, dtype: int64

In [ ]:
# Divide dataset into training and testing

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.2,
    random_state=42
)

# Display shapes(rows, columns)
print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (320, 2)
X_test: (80, 2)
y_train: (320,)
y_test: (80,)

In [ ]:
# Create scaler object
sc = StandardScaler()

# Scale training data
X_train = sc.fit_transform(X_train)

# Scale testing data
X_test = sc.transform(X_test)

print("Feature Scaling Completed")

Feature Scaling Completed

In [ ]:
# Create model
model = LogisticRegression()

print("Model Created")

Model Created

In [ ]:
# Train model
model.fit(X_train, y_train)

print("Model Training Completed")

Model Training Completed

In [ ]:
# Predict results
y_pred = model.predict(X_test)

# Display predictions
print(y_pred[:10])

[0 1 0 1 0 0 1 0 0 0]

In [ ]:
# Create confusion matrix
cm = confusion_matrix(y_test, y_pred)

print(cm)

[[50  2]
 [ 9 19]]

In [ ]:
# Accuracy score
accuracy = accuracy_score(y_test, y_pred)

print("Accuracy:", accuracy)

Accuracy: 0.8625

In [ ]:
# Precision score
precision = precision_score(y_test, y_pred)

print("Precision:", precision)

Precision: 0.9047619047619048

In [ ]:
# Recall score
recall = recall_score(y_test, y_pred)

print("Recall:", recall)

Recall: 0.6785714285714286

In [ ]:
# Compare actual and predicted values

comparison = pd.DataFrame({
    'Actual': y_test.values,
    'Predicted': y_pred
})

comparison.head(10)

   Actual  Predicted
0       0          0
1       1          1
2       0          0
3       1          1
4       0          0
5       0          0
6       1          1
7       0          0
8       0          0
9       0          0