In [ ]:
import pandas as pd
import numpy as np

np.random.seed(0)

df = pd.DataFrame({
    'age': np.random.randint(17, 25, 50),
    'study_hours': np.random.randint(1, 10, 50),
    'attendance': np.random.randint(50, 100, 50),
    'gpa': np.random.uniform(5, 10, 50),
    'marks': np.random.randint(40, 100, 50)
})

df.head()

   age  study_hours  attendance       gpa  marks
0   21            1          80  5.732209     77
1   24            2          50  7.848092     68
2   22            1          99  8.518686     87
3   17            5          86  6.442382     80
4   20            8          84  7.166440     42

In [ ]:
print(df.isnull().sum())

age            0
study_hours    0
attendance     0
gpa            0
marks          0
dtype: int64

In [ ]:
# STEP 1: Create missing values
df.loc[0, 'marks'] = np.nan
df.loc[1, 'gpa'] = np.nan

In [ ]:
print(df.isnull().sum())

age            0
study_hours    0
attendance     0
gpa            1
marks          1
dtype: int64

In [ ]:
# STEP 3: Handle missing values using mean
df['marks'].fillna(df['marks'].mean(), inplace=True)
df['gpa'].fillna(df['gpa'].mean(), inplace=True)

/tmp/ipykernel_627/55525604.py:2: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['marks'].fillna(df['marks'].mean(), inplace=True)
/tmp/ipykernel_627/55525604.py:3: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df['gpa'].fillna(df['gpa'].mean(), inplace=True)

In [ ]:
print(df.isnull().sum())

age            0
study_hours    0
attendance     0
gpa            0
marks          0
dtype: int64

In [ ]:
df.loc[0, 'marks'] = 500

In [ ]:
col = 'marks'

Q1 = df[col].quantile(0.25)
Q3 = df[col].quantile(0.75)

IQR = Q3 - Q1

lower = Q1 - 1.5 * IQR
upper = Q3 + 1.5 * IQR

outliers = df[(df[col] < lower) | (df[col] > upper)]

print("Lower:", lower)
print("Upper:", upper)
print("Outliers:\n", outliers)

Lower: 11.375
Upper: 122.375
Outliers:
    age  study_hours  attendance       gpa  marks
0   21            1          80  5.732209  500.0

In [ ]:
# STEP 6: handle (capping)
df[col] = np.where(df[col] > upper, upper, df[col])
df[col] = np.where(df[col] < lower, lower, df[col])

print("\nAfter capping:")
print(df.describe())

After capping:
             age  study_hours  attendance        gpa       marks
count  50.000000    50.000000      50.000  50.000000   50.000000
mean   20.480000     4.700000      75.480   7.426330   69.027500
std     2.426386     2.401105      15.454   1.346822   17.720536
min    17.000000     1.000000      50.000   5.168125   40.000000
25%    18.000000     3.000000      63.000   6.440562   53.000000
50%    20.000000     5.000000      79.500   7.296117   70.000000
75%    22.750000     6.000000      88.750   8.394507   80.750000
max    24.000000     9.000000      99.000   9.920211  122.375000

In [ ]:
df['study_hours_log'] = np.log1p(df['study_hours'])

In [ ]:
df[['study_hours', 'study_hours_log']].describe()

       study_hours  study_hours_log
count    50.000000        50.000000
mean      4.700000         1.632471
std       2.401105         0.500905
min       1.000000         0.693147
25%       3.000000         1.386294
50%       5.000000         1.791759
75%       6.000000         1.945910
max       9.000000         2.302585

In [ ]:
from sklearn.preprocessing import MinMaxScaler

scaler = MinMaxScaler()
df[['marks']] = scaler.fit_transform(df[['marks']])

In [ ]:
df.head()

   age  study_hours  attendance       gpa     marks  study_hours_log
0   21            1          80  5.732209  1.000000         0.693147
1   24            2          50  7.426330  0.339909         1.098612
2   22            1          99  8.518686  0.570561         0.693147
3   17            5          86  6.442382  0.485584         1.791759
4   20            8          84  7.166440  0.024279         2.197225